package project;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.LinkedList;
import java.util.ListIterator;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;

/**
 *
 * @author Vaibhav Pandya CS 530: Project
 */
public class YTForm extends javax.swing.JFrame {

	/**
	 * Creates new form YTForm
	 */
	public YTForm() {
		initComponents();
		// PlayPauseButton = new RoundButton("Play");
		// PlayPauseButton.setOpaque(false);
		// PlayPauseButton.setFocusPainted(false);
		// PlayPauseButton.setBorderPainted(false);
		// PlayPauseButton.setContentAreaFilled(false);
		// PlayPauseButton.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
		WaitLabel.setVisible(false);
		DownloadNotifyLabel.setVisible(false);
		DownloadingLabel.setText("");
		SaveLocationTextField.setText(System.getProperty("user.dir"));
		URLCheckButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(final ActionEvent e) {
				Thread qt = new Thread() {
					public void run() {
						WaitLabel.setVisible(true);
						DownloadNotifyLabel.setVisible(false);
						try {
							URLCheckButtonActionPerformed(e);
							WaitLabel.setVisible(false);
						} catch (Exception ex) {
							ex.printStackTrace();
						}
					}
				};
				qt.start();

			}
		});

		DownloadButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(final ActionEvent e) {
				Thread qt = new Thread() {
					public void run() {
						DownloadNotifyLabel.setVisible(true);
						try {
							DownloadButtonActionPerformed(e);
						} catch (Exception ex) {
							ex.printStackTrace();
						}
					}
				};
				qt.start();

			}
		});
		RemoveButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// DownloadNotifyLabel.setVisible(true);
				try {
					RemoveButtonActionPerformed(e);
				} catch (Exception ex) {
					ex.printStackTrace();
				}
			}
		});

		PlayPauseButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// DownloadNotifyLabel.setVisible(true);
				try {
					PlayPauseButtonActionPerformed(e);
				} catch (Exception ex) {
					ex.printStackTrace();
				}
			}
		});
	}

	DefaultListModel<String> ds = new DefaultListModel<String>();
	DefaultListModel<String> ds2 = new DefaultListModel<String>();
	youtubedl obj;
	LinkedList<youtubedl> dlq = new LinkedList<youtubedl>();
	boolean done = true;

	// Player pl;
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		YTSloganLabel = new javax.swing.JLabel();
		MainTabbedPane = new javax.swing.JTabbedPane();
		DownloadPanelTab = new javax.swing.JPanel();
		URLTextField = new javax.swing.JTextField();
		URLCheckButton = new javax.swing.JButton();
		SaveLocationTextField = new javax.swing.JTextField();
		SaveButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		AudioFormatList = new javax.swing.JList();
		AudioFormatLabel = new javax.swing.JLabel();
		FileNameTextField = new javax.swing.JTextField();
		FilenameLabel = new javax.swing.JLabel();
		DownloadButton = new javax.swing.JButton();
		DownloadNotifyLabel = new javax.swing.JLabel();
		WaitLabel = new javax.swing.JLabel();
		DLQueueTab = new javax.swing.JPanel();
		DownloadProgressbar = new javax.swing.JProgressBar();
		RemoveButton = new javax.swing.JButton();
		DownloadingLabel = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		TableDownload = new javax.swing.JTable();
		PlayPanelTab = new javax.swing.JPanel();
		jScrollPane4 = new javax.swing.JScrollPane();
		TablePlay = new javax.swing.JTable();
		PlayPauseButton = new javax.swing.JButton();
		StopButton = new javax.swing.JButton();
		jSlider1 = new javax.swing.JSlider();
		jLabel2 = new javax.swing.JLabel();
		BottomTagLabel = new javax.swing.JLabel();

		jLabel1.setText("jLabel1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 0, 0));
		setForeground(new java.awt.Color(0, 0, 0));
		setPreferredSize(new java.awt.Dimension(550, 500));
		setResizable(false);

		YTSloganLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		YTSloganLabel.setText("Instantly get mp3 from your favorite YT videos");

		MainTabbedPane.setBackground(new java.awt.Color(102, 102, 102));
		MainTabbedPane.setBorder(new javax.swing.border.MatteBorder(null));

		DownloadPanelTab.setBackground(new java.awt.Color(153, 153, 153));

		URLTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		URLTextField.setToolTipText("URL");
		URLTextField.setPreferredSize(new java.awt.Dimension(6, 23));

		URLCheckButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		URLCheckButton.setText("Check");

		SaveLocationTextField.setEditable(false);
		SaveLocationTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		SaveLocationTextField.setToolTipText("URL");

		SaveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		SaveButton.setText("Save");

		AudioFormatList.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
		AudioFormatList.setModel(ds);
		jScrollPane1.setViewportView(AudioFormatList);

		AudioFormatLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		AudioFormatLabel.setForeground(new java.awt.Color(255, 255, 255));
		AudioFormatLabel.setText("Choose audio format/quality:");
		AudioFormatLabel.setToolTipText("");

		FileNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		FileNameTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				FileNameTextFieldActionPerformed(evt);
			}
		});

		FilenameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		FilenameLabel.setForeground(new java.awt.Color(255, 255, 255));
		FilenameLabel.setText("Name your file:");

		DownloadButton.setBackground(new java.awt.Color(0, 153, 0));
		DownloadButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		DownloadButton.setForeground(new java.awt.Color(255, 255, 255));
		DownloadButton.setText("Download");

		DownloadNotifyLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		DownloadNotifyLabel.setForeground(new java.awt.Color(204, 0, 0));
		DownloadNotifyLabel.setText("Download added to Queue..");

		WaitLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		WaitLabel.setForeground(new java.awt.Color(255, 0, 0));
		WaitLabel.setText("Please Wait...");

		javax.swing.GroupLayout DownloadPanelTabLayout = new javax.swing.GroupLayout(DownloadPanelTab);
		DownloadPanelTab.setLayout(DownloadPanelTabLayout);
		DownloadPanelTabLayout.setHorizontalGroup(DownloadPanelTabLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(DownloadPanelTabLayout.createSequentialGroup().addContainerGap()
						.addGroup(DownloadPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(DownloadPanelTabLayout.createSequentialGroup()
										.addComponent(URLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 409,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(URLCheckButton))
								.addGroup(DownloadPanelTabLayout.createSequentialGroup()
										.addComponent(SaveLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
												409, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(SaveButton))
								.addGroup(DownloadPanelTabLayout.createSequentialGroup()
										.addGroup(DownloadPanelTabLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228,
														javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(AudioFormatLabel))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(DownloadPanelTabLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(DownloadPanelTabLayout.createSequentialGroup()
														.addComponent(FilenameLabel).addGap(0, 0, Short.MAX_VALUE))
												.addComponent(FileNameTextField).addComponent(DownloadButton,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addGroup(DownloadPanelTabLayout.createSequentialGroup().addComponent(WaitLabel)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(DownloadNotifyLabel).addGap(61, 61, 61)))));
		DownloadPanelTabLayout
				.setVerticalGroup(DownloadPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(DownloadPanelTabLayout.createSequentialGroup().addContainerGap()
								.addGroup(DownloadPanelTabLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(URLTextField, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(URLCheckButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30,
										Short.MAX_VALUE))
						.addGap(18, 18, 18)
						.addGroup(DownloadPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(SaveLocationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30,
										Short.MAX_VALUE)
								.addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
						.addGap(3, 3, 3)
						.addGroup(DownloadPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(AudioFormatLabel).addComponent(FilenameLabel))
						.addGap(1, 1, 1)
						.addGroup(DownloadPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(DownloadPanelTabLayout.createSequentialGroup()
										.addComponent(FileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(120, 120, 120).addComponent(DownloadButton,
												javax.swing.GroupLayout.PREFERRED_SIZE, 61,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1432, Short.MAX_VALUE)
						.addGroup(DownloadPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(DownloadNotifyLabel).addComponent(WaitLabel)).addContainerGap()));

		MainTabbedPane.addTab("Download", DownloadPanelTab);

		DLQueueTab.setBackground(new java.awt.Color(153, 153, 153));
		DLQueueTab.setMaximumSize(new java.awt.Dimension(500, 500));
		DLQueueTab.setPreferredSize(new java.awt.Dimension(500, 500));

		DownloadProgressbar.setBackground(new java.awt.Color(204, 0, 0));
		DownloadProgressbar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		DownloadProgressbar.setForeground(new java.awt.Color(0, 0, 0));
		DownloadProgressbar.setToolTipText("");
		DownloadProgressbar.setStringPainted(true);

		RemoveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		RemoveButton.setText("Remove");

		DownloadingLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		DownloadingLabel.setForeground(new java.awt.Color(0, 204, 0));
		DownloadingLabel.setText("Downloading..");

		TableDownload.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "File Name", "Status" }) {
			boolean[] canEdit = new boolean[] { false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane3.setViewportView(TableDownload);
		TableDownload.getColumnModel().getColumn(0).setPreferredWidth(50);
		TableDownload.getColumnModel().getColumn(1).setPreferredWidth(10);

		javax.swing.GroupLayout DLQueueTabLayout = new javax.swing.GroupLayout(DLQueueTab);
		DLQueueTab.setLayout(DLQueueTabLayout);
		DLQueueTabLayout.setHorizontalGroup(DLQueueTabLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(DownloadProgressbar, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
				.addGroup(DLQueueTabLayout.createSequentialGroup().addContainerGap()
						.addGroup(DLQueueTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(DLQueueTabLayout.createSequentialGroup()
										.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
												Short.MAX_VALUE)
										.addGap(18, 18, 18)
										.addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(DLQueueTabLayout.createSequentialGroup().addComponent(DownloadingLabel).addGap(0, 0,
								Short.MAX_VALUE)))
						.addContainerGap()));
		DLQueueTabLayout.setVerticalGroup(DLQueueTabLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(DLQueueTabLayout.createSequentialGroup().addContainerGap()
						.addGroup(DLQueueTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(RemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(DownloadingLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(DownloadProgressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(1436, Short.MAX_VALUE)));

		MainTabbedPane.addTab("DL Queue", DLQueueTab);

		PlayPanelTab.setBackground(new java.awt.Color(153, 153, 153));

		TablePlay.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Name", "" }) {
			boolean[] canEdit = new boolean[] { false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane4.setViewportView(TablePlay);
		TablePlay.getColumnModel().getColumn(0).setPreferredWidth(50);
		TablePlay.getColumnModel().getColumn(1).setPreferredWidth(10);

		PlayPauseButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		PlayPauseButton.setText("Play");
		PlayPauseButton.setPreferredSize(new java.awt.Dimension(70, 30));

		StopButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		StopButton.setText("Stop");

		jSlider1.setValue(0);

		javax.swing.GroupLayout PlayPanelTabLayout = new javax.swing.GroupLayout(PlayPanelTab);
		PlayPanelTab.setLayout(PlayPanelTabLayout);
		PlayPanelTabLayout.setHorizontalGroup(PlayPanelTabLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(PlayPanelTabLayout.createSequentialGroup()
						.addGroup(PlayPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(PlayPanelTabLayout.createSequentialGroup().addGap(162, 162, 162)
										.addComponent(PlayPauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(StopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(PlayPanelTabLayout.createSequentialGroup().addContainerGap()
										.addGroup(PlayPanelTabLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jSlider1, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 480,
														Short.MAX_VALUE))))
						.addContainerGap()));
		PlayPanelTabLayout
				.setVerticalGroup(PlayPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(PlayPanelTabLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 259,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(PlayPanelTabLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(PlayPauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44,
										Short.MAX_VALUE)
								.addComponent(StopButton, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap(1429, Short.MAX_VALUE)));

		MainTabbedPane.addTab("Play", PlayPanelTab);

		jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vaibhav\\Desktop\\unnamed.png")); // NOI18N

		BottomTagLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
		BottomTagLabel.setText("ALL THE MUSIC. ALL THE FUN. ALL FOR FREE");
		BottomTagLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel2).addGap(33, 33, 33).addComponent(YTSloganLabel).addGap(43, 43, 43))
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(MainTabbedPane).addComponent(BottomTagLabel,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addGap(19, 19, 19)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(YTSloganLabel).addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE, 40,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(MainTabbedPane)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(BottomTagLabel).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void FileNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FileNameTextFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_FileNameTextFieldActionPerformed

	private void DownloadButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		// TODO add your handling code here:
		// MainTabbedPane.setSelectedIndex(1);

		DefaultTableModel model = (DefaultTableModel) TableDownload.getModel();
		DefaultTableModel model2 = (DefaultTableModel) TablePlay.getModel();

		obj.fName = FileNameTextField.getText();
		obj.SelInd = AudioFormatList.getSelectedIndex() + 1;
		obj.status = "Waiting";
		obj.indx = ind;
		ind++;
		// obj.indx=
		dlq.add(obj);
		// ListIterator<youtubedl> li = dlq.listIterator();
		model.addRow(new Object[] { obj.fName, obj.status });
		// ds2.addElement(obj.fName+"----------------"+obj.status);
		if (done == true) {
			done = false;
			// for(int x=0;x<dlq.size();x++){
			while (!dlq.isEmpty()) {
				youtubedl temp = dlq.removeFirst();
				DownloadingLabel.setText("Downloading...");
				// dlq.get(x).status="Downloading";
				// DownloadQueueList.setSelectedIndex(x);
				// ds2.setElementAt(dlq.get(x).fName+"-----------------Downloading",x);
				model.setValueAt("Downloading", temp.indx, 1);
				try {
					// dlq.get(x).download(dlq.get(x).SelInd,dlq.get(x).fName,DownloadProgressbar);
					temp.download(temp.SelInd, temp.fName, DownloadProgressbar);
					DownloadingLabel.setText("Download Complete!!");
					// dlq.get(x).status="Done";
					// ds2.setElementAt(dlq.get(x).fName+"-----------------Completed",x);
					model.setValueAt("Completed", temp.indx, 1);
					model2.addRow(new Object[] { model.getValueAt(temp.indx, 0), "" });
					// dlq.removeFirst();
				} catch (Exception e) {
					// ds2.setElementAt(dlq.get(x).fName+"-----------------Error:Cant
					// download due to YouTube restrictions!",x);
					model.setValueAt("Error:Cant download due to YouTube restrictions!", temp.indx, 1);
				}
				//
			}
			done = true;
		}
	}

	private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		DefaultTableModel model = (DefaultTableModel) TableDownload.getModel();
		// ds2.remove(DownloadQueueList.getSelectedIndex());
		model.removeRow(TableDownload.getSelectedRow());
		// dlq.remove(TableDownload.getSelectedRow());

	}

	private void PlayPauseButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {

		// new Player("");

	}

	int ind = 0;

	private void URLCheckButtonActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		// TODO add your handling code here:
		// WaitLabel.setVisible(true);
		// this.repaint();
		ds.clear();
		obj = new youtubedl(new URL(URLTextField.getText()));

		// obj = new youtubedl(new
		// URL("https://www.youtube.com/watch?v=cOsqdghHcIk")); works glass
		// // youtubedl obj = new youtubedl(new
		// URL("https://www.youtube.com/watch?v=zdkpHaC7Ogo"));
		// https://www.youtube.com/watch?v=RiVKDn5kyfo&list=PLYiUhQLFA05uY8Fk8sR1mK_McHY17jXpI
		// ; works landen

		obj.GetDownloadIndex();
		obj.displayIndex(ds);
		AudioFormatList.setSelectedIndex(0);

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) throws Exception {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(YTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(YTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(YTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(YTForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new YTForm().setVisible(true);
			}
		});

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel AudioFormatLabel;
	public javax.swing.JList AudioFormatList;
	private javax.swing.JLabel BottomTagLabel;
	private javax.swing.JPanel DLQueueTab;
	private javax.swing.JButton DownloadButton;
	private javax.swing.JLabel DownloadNotifyLabel;
	private javax.swing.JPanel DownloadPanelTab;
	private javax.swing.JProgressBar DownloadProgressbar;
	private javax.swing.JLabel DownloadingLabel;
	private javax.swing.JTextField FileNameTextField;
	private javax.swing.JLabel FilenameLabel;
	private javax.swing.JTabbedPane MainTabbedPane;
	private javax.swing.JPanel PlayPanelTab;
	private javax.swing.JButton PlayPauseButton;
	private javax.swing.JButton RemoveButton;
	private javax.swing.JButton SaveButton;
	private javax.swing.JTextField SaveLocationTextField;
	private javax.swing.JButton StopButton;
	private javax.swing.JTable TableDownload;
	private javax.swing.JTable TablePlay;
	private javax.swing.JButton URLCheckButton;
	private javax.swing.JTextField URLTextField;
	private javax.swing.JLabel WaitLabel;
	private javax.swing.JLabel YTSloganLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JSlider jSlider1;
	// End of variables declaration//GEN-END:variables
}
